{% set name = "panel-material-ui" %}
{% set version = "0.14.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4b4e9d6f771294d778b6c13ea77348a633d55e48264dfa803f4d8bbd9d5ebf6a

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    # As defined in upstream conda-forge:
    # https://github.com/conda-forge/panel-material-ui-feedstock/blob/01ec45b791c318e6130da688503f5653f421388a/recipe/meta.yaml#L23
    # uses panel >=1.8.0 lead to depend-on-themselves problem.
    - panel-core >=1.8.0
    # https://github.com/conda-forge/panel-material-ui-feedstock/blob/01ec45b791c318e6130da688503f5653f421388a/recipe/meta.yaml#L24
    - nodejs >=22.*
    - esbuild 0.25.4
    - packaging
    - pip
    - panel >=1.8.0
  run:
    - python
    # As defined in upstream conda-forge:
    # https://github.com/conda-forge/panel-material-ui-feedstock/blob/01ec45b791c318e6130da688503f5653f421388a/recipe/meta.yaml#L30
    # uses panel >=1.8.0 lead to depend-on-themselves problem.
    - panel-core >=1.8.0
    - bokeh >=3.8.0
    - packaging
    - panel >=1.8.0

test:
  source_files:
    - tests
    - examples
    - doc
  imports:
    - panel_material_ui
  commands:
    - pip check
    - pytest --import-mode=importlib -ra -vv --tb=short tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - plotly

about:
  home: https://panel-material-ui.holoviz.org
  summary: An extension to bring MaterialUI components to Panel.
  description: |
    Panel Material UI is a modern theming and component library that brings the design
    system of Material UI to Panel-based dashboards and data applications. It provides
    a consistent look and feel, seamless dark-mode support, and full theming via
    Material UI's theme system (palette, typography, spacing). The library includes a
    rich set of ready-to-use UI components—such as buttons, sliders, cards, dialogs,
    menus, and grids—that integrate smoothly with Panel's layout and reactive model.
    With Panel Material UI, you can build modern, responsive, and branded dashboards
    in Python while leveraging Panel's ecosystem.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  dev_url: https://github.com/panel-extensions/panel-material-ui
  doc_url: https://panel-material-ui.holoviz.org/

extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - maximlt
    - philippjfr
    - hoxbro
