{% set name = "panel-material-ui" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel_material_ui-{{ version }}.tar.gz
  sha256: 8ca39c181fad38bb8289209a6013ce073d43c1c224cd1c1d03bf95b8622d6aa2

build:
  number: 0
  skip: True # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - panel >=1.8.0
    - nodejs 24.*
    - esbuild 0.25.4
    - packaging
    - pip
  run:
    - python
    - panel >=1.9.0
    - bokeh >=3.8.0
    - packaging

test:
  source_files:
    - tests
    - examples
    - doc
  imports:
    - panel_material_ui
  commands:
    - pip check
    - pytest --import-mode=importlib -ra -vv --tb=short tests
  requires:
    - pip
    - pytest
    - pytest-asyncio
    - plotly

about:
  home: https://panel-material-ui.holoviz.org
  summary: An extension to bring MaterialUI components to Panel.
  description: |
    Panel Material UI is a modern theming and component library that brings the design
    system of Material UI to Panel-based dashboards and data applications. It provides
    a consistent look and feel, seamless dark-mode support, and full theming via
    Material UI's theme system (palette, typography, spacing). The library includes a
    rich set of ready-to-use UI components—such as buttons, sliders, cards, dialogs,
    menus, and grids—that integrate smoothly with Panel's layout and reactive model.
    With Panel Material UI, you can build modern, responsive, and branded dashboards
    in Python while leveraging Panel's ecosystem.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  dev_url: https://github.com/panel-extensions/panel-material-ui
  doc_url: https://panel-material-ui.holoviz.org/


extra:
  skip-lints:
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - maximlt
    - philippjfr
    - hoxbro
