{% set name = "panel-material-ui" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/panel_material_ui-{{ version }}.tar.gz
  sha256: 78ab1078ed88f4fc825ee5b553f26cca6647085ca17299c530c1c50de4dde666

build:
  number: 1
  skip: True # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - hatchling
    - hatch-vcs
    - panel >=1.8.0
    - nodejs 24.*
    - esbuild 0.25.4
    - packaging
    - pip
  run:
    - python
    - panel >=1.8.0
    - bokeh >=3.8.0
    - packaging

test:
  imports:
    - panel_material_ui
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://panel-material-ui.holoviz.org
  summary: An extension to bring MaterialUI components to Panel.
  description: |
    Panel Material UI is a modern theming and component library that brings the design
    system of Material UI to Panel-based dashboards and data applications. It provides
    a consistent look and feel, seamless dark-mode support, and full theming via
    Material UI’s theme system (palette, typography, spacing). The library includes a
    rich set of ready-to-use UI components—such as buttons, sliders, cards, dialogs,
    menus, and grids—that integrate smoothly with Panel’s layout and reactive model.
    With Panel Material UI, you can build modern, responsive, and branded dashboards
    in Python while leveraging Panel’s ecosystem.
  dev_url: https://github.com/panel-extensions/panel-material-ui
  license: BSD-3-Clause
  license_file: LICENSE.txt
  license_family: BSD
  dev_url: https://github.com/panel-extensions/panel-material-ui
  doc_url: https://panel-material-ui.holoviz.org/


extra:
  recipe-maintainers:
    - maximlt
    - philippjfr
    - hoxbro
